[package]
name = "grug-ls"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
serde = {version = "1.0.219", features=["derive"]}
serde_json = "1.0.143"
tree-sitter = "0.25.8"
tree-sitter-grug = "0.2.1"
vfs = "0.12.2"
